# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mai's Escapade
email: 1612162886@qq.com
description:  # this means to ignore newlines until "baseurl:"
  麦花喵~
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ystkc.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
# Use --no-watch to disable livereload


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - examples/
  - temp/
  - milestones/
  - "*.txt"
  - "*.db"
  - "*.db-journal"
  - "*.lnk"
  - "*.bin"
  - "*.py"
  - "*.xlsx"
  - "*.csv"
  - "*.rar" # For archives. Assets should be in zip files.
  - "*.sh"
  - "*.bat"
  - l_BaseKit_p_2024.2.1.100_offline/
  - intel-extension-for-tensorflow/
  - tdf_env/
  - blacklist_rating.json
  - patterns copy.json
  - patterns.json
  - assets/enhanced_bad_words.json
  - assets/accept_words.json
  - assets/bad_words.json
  - assets/warn_words.json
  - assets/member/old/
  - assets/member_name/old/
